project-name: thanethomson.com
base-path: /
encoding: utf-8
markdown:
  permalinks:
    enabled: true
    class: permalink
    title: Permalink to this heading
    text: "#"
context:
  static:
    site-description: >
      I enjoy creating useful things for people, and sometimes I like to
      write about stuff too.
    production: false
    disqus-user-id: useridhere
